### ISSUE TITLE
Use ui-router instead ngRoute

### ISSUE THREAD

**Issue by TsarS** [Selmanh/angularjs-form-builder#14]
Thanks for your form-builder.
Can i use ui-router instead ngRoute?
It seems to me i need change only $routeParams on $stateParams view.js in
    FormService.form($stateParams.id).then(function(form) {
		$scope.form = form;
	}); ?

**Comment by Selmanh** [comment]
This is a simple demonstraion of how you can create a form builder using AngularJS. You can definitely fork and use ui-router if that fits in your project.
