### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by matrinox** [Selmanh/angularjs-form-builder#15]
To add a custom field would require forking this repo. Would it be possible to be able to register templates in the config phase?

Or follow Convention-Over-Configuration and just append the field type name to the templateUrl.

**Comment by Selmanh** [comment]
As this is not a 3rd party library, you anyway would need to fork it and copy-paste the code you need and use the similar logic within your AngularJS app. 

This is exactly what it does right now; appends the field type name to the url and gets the field markup.
